# Generated by Django 5.2.1 on 2025-06-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.modelo'),
        ),
    ]
