# Generated by Django 5.2.1 on 2025-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_leasing_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='status',
            field=models.CharField(choices=[('home office', ' Home office'), ('devoldido', 'Devolvido')], default='alugado', max_length=20),
        ),
    ]
