# Generated by Django 5.2.1 on 2025-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_alter_leasing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
