# Generated by Django 5.2.1 on 2025-06-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_leasing_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasing',
            old_name='observações',
            new_name='observacoes',
        ),
    ]
