# Generated by Django 5.2.1 on 2025-06-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_rename_observações_leasing_observacoes'),
        ('user', '0003_remove_usuario_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasing',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='status',
        ),
        migrations.AddField(
            model_name='leasing',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usuario'),
        ),
    ]
