# Generated by Django 5.2.1 on 2025-06-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_remove_leasing_data_fim_remove_leasing_data_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasing',
            old_name='observacoes',
            new_name='Defeito',
        ),
    ]
