# Generated by Django 5.2.1 on 2025-06-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_rename_observacoes_leasing_defeito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasing',
            old_name='Defeito',
            new_name='cidade',
        ),
    ]
