# Generated by Django 5.2.1 on 2025-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_leasing_observações'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='cidade',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
    ]
