# Generated by Django 5.2.1 on 2025-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_alter_leasing_cidade_alter_leasing_observações'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leasing',
            name='home_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
