# Generated by Django 5.2.3 on 2025-06-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_leasing_ativo_leasing_home_office_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasing',
            old_name='observações',
            new_name='observacoes',
        ),
    ]
