# Generated by Django 5.2.1 on 2025-06-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='nome',
            new_name='marca',
        ),
    ]
