# Generated by Django 5.2.1 on 2025-06-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_rename_nome_modelo_marca'),
        ('notebook', '0003_notebook_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='notebook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_relacionado', to='notebook.notebook'),
        ),
    ]
