# Generated by Django 5.2.1 on 2025-06-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_modelo_notebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='marca',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='notebook',
        ),
    ]
