# Generated by Django 5.2.1 on 2025-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_rename_marca_modelo_modelo_remove_modelo_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
