# Generated by Django 5.2.1 on 2025-06-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_alter_modelo_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='quantidade',
        ),
    ]
