# Generated by Django 5.2.1 on 2025-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_remove_modelo_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
