# Generated by Django 5.2.1 on 2025-06-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
