# Generated by Django 5.2.1 on 2025-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_entrada_observações_alter_entrada_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='modelo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
