# Generated by Django 5.2.1 on 2025-06-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_alter_entrada_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='notebook',
        ),
    ]
