# Generated by Django 5.2.3 on 2025-06-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_remove_entrada_notebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='observações',
            new_name='observacoes',
        ),
    ]
