# Generated by Django 5.2.1 on 2025-06-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebook', '0003_notebook_modelo'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('manutenção', 'Manutenção'), ('perda', 'Perda'), ('defeito', 'Defeito'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usuario')),
            ],
        ),
    ]
