# Generated by Django 5.2.1 on 2025-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
