# Generated by Django 5.2.1 on 2025-06-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0008_remove_notebook_descricao'),
        ('ocorrencia', '0002_alter_ocorrencia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook'),
        ),
    ]
