# Generated by Django 5.2.1 on 2025-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_alter_ocorrencia_notebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='descricao',
            new_name='observação',
        ),
    ]
