# Generated by Django 5.2.1 on 2025-06-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_rename_descricao_ocorrencia_observação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='resolvido',
        ),
    ]
