# Generated by Django 5.2.1 on 2025-06-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_remove_ocorrencia_resolvido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='observação',
            new_name='observacao',
        ),
    ]
