# Generated by Django 5.2.1 on 2025-06-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='notebook',
        ),
    ]
