# Generated by Django 5.2.1 on 2025-06-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
        ('notebook', '0002_remove_notebook_categoria_notebook_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.modelo'),
        ),
    ]
