# Generated by Django 5.2.1 on 2025-06-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_modelo_notebook'),
        ('notebook', '0003_notebook_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='modelo.modelo'),
        ),
    ]
