# Generated by Django 5.2.1 on 2025-06-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_alter_notebook_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='preco',
        ),
    ]
