# Generated by Django 5.2.1 on 2025-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_remove_notebook_nome_remove_notebook_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
