# Generated by Django 5.2.1 on 2025-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_alter_notebook_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
