# Generated by Django 5.2.1 on 2025-06-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_notebook_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='descricao',
        ),
    ]
