# Generated by Django 5.2.3 on 2025-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0008_remove_notebook_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
